# Generated by Django 4.1.1 on 2022-09-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
